name: Run dbt models on schedule

on:
  schedule:
    - cron: '0 14 */2 * *'  # Runs every other day at 8 AM CST
  workflow_dispatch:

jobs:
  run-dbt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install dbt
        run: pip install dbt-core dbt-snowflake

      - name: Configure dbt profiles
        run: |
          mkdir -p ~/.dbt
          echo "${{ secrets.DBT_PROFILES_YML }}" > ~/.dbt/profiles.yml
          chmod 600 ~/.dbt/profiles.yml  # Secure the file permissions

      - name: Install dbt dependencies
        run: |
          rm -rf dbt_packages  # Clear existing dbt packages
          dbt deps --project-dir dbt_scraper

      - name: Check dbt packages directory
        run: ls -la dbt_scraper/dbt_packages || echo "dbt_packages not found"

      - name: Run dbt models
        run: dbt run --project-dir dbt_scraper
